### ISSUE TITLE
Route for tracking opens, is different than the one rendered in the template

### ISSUE THREAD

**Issue by bo-oz** [ankane/ahoy_email#129]
Hi,

The open tracking pixel is rendered like `/messages/SomeKindOfToken/open.gif`, while the actual route that seems to be created by default in my app is: `/ahoy/messages/SomeKindOfToken/open/gif`. Is this a bug, or should I configure it differently somehow?

Thanks.

**Comment by ankane** [comment]
Hey @bo-oz, are you able to reproduce with a fresh app?

**Comment by maxxsnake** [comment]
This happens when `AhoyEmail.api = true` hasn't been set in an initializer. I assumed the value was for the purpose of setting up endpoints which respond to the generated URLs (which in my case happens in a separate application), but evidently it also plays a role in how to generate that URL.

**Comment by ankane** [comment]
Thanks for the update @maxxsnake. That makes sense, since there's no way to know the path if the engine isn't mounted. I'm surprised Rails doesn't throw an error in this situation. Ahoy Email could throw an error, but after a quick search, I'm not sure there's a good way to tell if a Rails engine is mounted.

Related: https://github.com/rails/rails/issues/4940
